### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by thundergolfer** [kalregi/What-sWrong_SVG#1]
I see that the last commit was 4 months ago in December of 2016. Is it still being worked on, and what's the current progress? The repo could do with some more documentation.

**Comment by dlazesz** [comment]
Hi!
This repository contains the BSc thesis of Regina Klacsevszki.
The final state of the program.
The actual program is being further developed.
 Please consider checking the following repository for the current state of the program (still in development):
https://github.com/ppke-nlpg/What-sWrong_SVG

I'll update the README.md for clarity.

**Comment by dlazesz** [comment]
Done in ff60fa2b75fb3486517085e34ece153b0e2606c5
